id: D73352AE0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:08:52+00:00'
last_modified: '2022-05-30T06:30:26.657160+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a1b4:
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་འབྱུང་བའི་སྨོན་ལམ།
      total_pages: 1880
      order: 116
      base_file: a1b4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
