id: PEDE0DDAD
initial_creation_type: ocr
source_metadata:
  volumes:
    0f65854cae9b4c559b9fe47c65026a01:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: བྱང་ཆུབ་འབྱུང་བའི་སྨོན་ལམ།
      total_pages: 1880
      volume_number: 116
